all:
  children:

    infrastructure:
      children:

        network:
          children:
            routers:
              hosts: {}
            switches:
              hosts: {}
            aps:
              hosts: {}

        compute:
          hosts: {}

        storage:
          hosts: {}

        control_plane:
          hosts: {}
