all:
  children:
    builder:
      hosts:
        admin02:
          ansible_host: 192.168.10.97
          hostname: vdvntm-admin-02
        admin03:
          ansible_host: 192.168.10.96
          hostname: vdvntm-admin-03
        admin04:
          ansible_host: 192.168.10.95
          hostname: vdvntm-admin-04

    workstations:
      hosts:
        admin02:
        admin03:
        admin04:

    artifact_servers:
      hosts:
        admin02:
        admin04:

    network_controllers:
      hosts:
#        admin02:
        admin04:
        
    bootstrap_nodes:
      hosts:
        admin02:
        admin04: