all:
  children:
    admin:
      hosts:
        admin02:
          ansible_host: 192.168.10.97
          hostname: vdvntm-admin-02
        admin03:
          ansible_host: 192.168.10.96
          hostname: vdvntm-admin-03