all:
  children:

    infrastructure:
      children:

        network:
          children:
            routers:
              hosts:
                edge-rt01: {}
                core-rt02: {}

            dns_servers:
              hosts:
                core-rt02: {}

            dhcp_servers:
              hosts:
                core-rt02: {}

            switches:
              hosts:
                access-sw01: {}

            aps:
              hosts:
                ap01: {}

        compute:
          children:
            hypervisors:
              hosts:
                hv01: {}
                hv02: {}

            pis:
              hosts:
                pi01: {}
                pi02: {}
                pi03: {}
                pi04: {}

        storage:
          hosts: {}

        control_plane:
          hosts:
            provisioner-vm02: {}
            provisioner-vm03: {}

        oob_management:
          hosts:
            provisioner-ph01: {}

        edge_devices:
          hosts: {}
          # examples later:
          # jetson-em01: {}
          # mabell-em02: {}
          # console-pi05: {}

    # --- Functional / intent-based groupings (orthogonal) ---
    workstations:
      hosts:
        provisioner-ph01: {}
        provisioner-vm02: {}
        provisioner-vm03: {}

    artifact_servers:
      hosts:
        provisioner-ph01: {}
        provisioner-vm02: {}
        provisioner-vm03: {}

    bootstrap_nodes:
      hosts:
        provisioner-ph01: {}
        provisioner-vm02: {}
        provisioner-vm03: {}
