infrastructure:
  form: pi
  interfaces:
    eth0:
      mac: "dc:a6:32:c5:a1:a6"

env:
  interfaces:
    eth0:
      ip: 10.20.30.14
      purpose: mgmt
      segment: iot
      dns:
        host_a_record: true
        dhcp_reservation: true
