#!/usr/bin/env python3
"""Write vault.example.yml beside every decrypted vault.yml: the same keys and
comments, with every value emptied.

Maintainer tool: run with the vaults decrypted (`make unvault`). A new site
starts from the examples with scripts/make-empty-vault.sh.

Refuses to write anything if a comment holds something that looks like a
secret (a long run of key-like characters), so a value pasted into a comment
is never published. Review the diff before committing regardless.
"""
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
KEY = re.compile(r"^(#\s*)?([A-Za-z_][A-Za-z0-9_]*):(\s*)(.*)$")
SECRETISH = re.compile(r"[A-Za-z0-9+/=_\-]{24,}")
HEADER = (
    "# Example vault: every key this vault holds, with its value emptied.\n"
    "# A new site copies it to vault.yml (scripts/make-empty-vault.sh), fills it in,\n"
    "# and runs `make vault` before committing. Generated by scripts/vault-examples.py.\n"
    "\n"
)


NESTED = re.compile(r"^(\s+)([A-Za-z_][A-Za-z0-9_-]*):(\s*)(.*)$")


CONFIG = yaml.safe_load((ROOT / "scripts" / "vault-examples.yml").read_text())
DROP = [p.lower() for p in CONFIG.get("drop_paragraphs_matching", [])]
HINTS = CONFIG.get("hints", {})


def drop_private(lines):
    """Remove comment paragraphs that match a drop phrase."""
    out, para = [], []

    def flush():
        if not any(d in "\n".join(para).lower() for d in DROP):
            out.extend(para)
        para.clear()

    for line in lines:
        s = line.strip()
        if s.startswith("#") and s != "#":
            para.append(line)
            continue
        flush()
        out.append(line)
    flush()
    # collapse a run of blank "#" lines left behind by a dropped paragraph
    tidy = []
    for line in out:
        if line.strip() == "#" and tidy and tidy[-1].strip() == "#":
            continue
        tidy.append(line)
    return tidy


def add_hints(lines):
    """Put a hint above a key that has no comment of its own."""
    out = []
    for line in lines:
        m = KEY.match(line)
        if m and not m.group(1) and m.group(2) in HINTS:
            if not (out and out[-1].lstrip().startswith("#")):
                out.extend("# " + h if h else "#" for h in HINTS[m.group(2)].split("\n"))
        out.append(line)
    return out


def example(text, path):
    text = "\n".join(drop_private(text.splitlines()))
    out, problems = [], []
    in_map = False  # inside a top-level key whose value is a mapping
    for n, line in enumerate(text.splitlines(), 1):
        stripped = line.lstrip()
        if line[:1] in (" ", "\t"):
            if stripped.startswith("#"):
                out.append(line)
            elif in_map and (m := NESTED.match(line)):
                # keep the mapping's keys (e.g. one Wi-Fi key per VLAN), empty the values
                out.append(f'{m.group(1)}{m.group(2)}: ""')
            # anything else continues a multi-line value, and is dropped with it
            continue
        m = KEY.match(line)
        # A commented-out line counts as a key only if it names a vault
        # variable; otherwise it is prose that happens to contain a colon.
        if m and (not m.group(1) or m.group(2).startswith("vault_")):
            comment, key, value = m.group(1) or "", m.group(2), m.group(4).strip()
            in_map = not comment and value == ""
            out.append(f"{comment}{key}:" if in_map else f'{comment}{key}: ""')
            continue
        if stripped.startswith("#"):
            for tok in SECRETISH.findall(line):
                # lowercase words, slugs and paths are fine; mixed case or long hex is not
                if not re.fullmatch(r"[a-z0-9_./\-]+", tok) or re.fullmatch(r"[0-9a-f]+", tok):
                    problems.append(f"{path}:{n}: looks like a secret: {tok[:6]}…")
        elif stripped:
            in_map = False
        out.append(line)
    out = add_hints(out)
    return HEADER + "\n".join(out).rstrip() + "\n", problems


def main():
    vaults = sorted(ROOT.glob("*/**/vault.yml"))
    results, problems = [], []
    for v in vaults:
        text = v.read_text()
        if text.startswith("$ANSIBLE_VAULT"):
            sys.exit(f"{v.relative_to(ROOT)} is encrypted: run `make unvault` first")
        ex, p = example(text, v.relative_to(ROOT))
        results.append((v.with_name("vault.example.yml"), ex))
        problems += p
    if problems:
        sys.exit("Nothing written:\n  " + "\n  ".join(problems))
    for path, ex in results:
        path.write_text(ex)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
