infrastructure:
  form: hv
  interfaces:
    eth0:
      mac: "d8:9e:f3:7d:94:c4"

env:
  interfaces:
    eth0:
      ip: 10.20.99.21
      purpose: mgmt
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
        cnames:
          - pve

proxmox_token_id: "{{ vault_proxmox_token_id }}"
proxmox_token_secret: "{{ vault_proxmox_token_secret }}"
